#!/usr/bin/expect

#set timeout to infinity
set timeout -1

#password are settin up as variables.
#set password [exec ./reading_pw.sh]

set secret_file [open "./opening_req.txt" r]
gets $secret_file username
gets $secret_file password
gets $secret_file servername
close $secret_file

# This bash command is connecting you to server
spawn ssh "${username}@${servername}"

#This is command's response
expect "*password: "
# and our reply
send -- "$password\n"
interact
