#!/usr/bin/expect

set timeout 5

#username and password are settin up as variables.
set secret_file [open "./opening_req.txt" r]
gets $secret_file username
gets $secret_file password
gets $secret_file dest
close $secret_file

# This bash command is connecting you to vpn
spawn openvpn --config "${dest}"

#This is command's response
expect "*Username: "
# and our reply
send -- "$username\n"
expect "*Password: "
send -- "$password\n"
interact
